### ISSUE TITLE
缺图片了

### ISSUE THREAD

**Issue by mengguyi** [Suto-Commune/Kindle-Reader-Web-CLI#21]
storage\assets\img\noCover.jpeg 似乎没有提交
<img width="1280" alt="image" src="https://github.com/Suto-Commune/Kindle-Reader-Web-CLI/assets/73788063/92fc0396-84bf-4028-9d56-1bfb53e515e3">

**Comment by NatsumiXD** [comment]
这是排除文件的锅（

**Comment by NatsumiXD** [comment]
我修一下

**Comment by mengguyi** [comment]
> 这是排除文件的锅（

还有这里 https://github.com/Suto-Commune/Kindle-Reader-Web-CLI/tree/main/head/__pycache__

**Comment by NatsumiXD** [comment]
可以了

**Comment by mengguyi** [comment]
> 可以了
__pycache__ 似乎还是存在
https://github.com/Suto-Commune/Kindle-Reader-Web-CLI/tree/main/head

**Comment by NatsumiXD** [comment]
好了
