### ISSUE TITLE
webdav同步书架信息（书架信息同步）

### ISSUE THREAD

**Issue by NatsumiXD** [Suto-Commune/Kindle-Reader-Web-CLI#6]

**Comment by miangou** [comment]
WebDAV同步配置
首先需要在阅读App里面配置 WebDAV备份

服务器地址： http://IP:端口/reader3/webdav/

如果开启了 reader.app.secure 选项，那么使用网页注册的用户名和密码登录，否则使用用户名 default 和 密码 123456 登录

然后在阅读App里面点击备份

在网页里面查看WebDAV文件，确认是否备份成功

备份成功之后

服务器会自动同步书籍阅读进度(暂不支持章节内阅读位置，也不会自动同步书架信息变更)

可以直接选择阅读App的备份文件进行恢复，这样会直接覆盖书源和书架信息

可以备份当前书源和书架信息到WebDAV，但是必须要先备份成功

需要通过恢复备份文件来同步书籍和书源信息

PS: 本地书源的书籍同步后无法打开，除非换源

**Comment by miangou** [comment]
不会自动同步书架信息变更

**Comment by miangou** [comment]
app端阅读失败并不能被正确引用
